### ISSUE TITLE
Be more friendly to packagers

### ISSUE THREAD

**Issue by williamjmorenor** [rumpelsepp/pynote#33]
Hi

I am packaging pynote, rpmlint show a issue for a missing manpage, can you add a manpage please.

Regards

https://bugzilla.redhat.com/show_bug.cgi?id=1229886

**Comment by rumpelsepp** [comment]
Hi,
you can use `make man` within the docs directory. There is sphinx required to build the manpages.

**Comment by rumpelsepp** [comment]
related to #34

**Comment by rumpelsepp** [comment]
@williamjmorenor: Don't know if it is still valid. I am working on version 2.0.0 now, where I heavily refactored pynote. The documentation is now generated with `asciidoctor` (you may use `asciidoc`as well). And a few dependencies have been dropped. You could have a look at the master branch. Let me know if you have any questions/suggestions.
