### ISSUE TITLE
Improve creation of a new note to create the .note and .trash dirs

### ISSUE THREAD

**Issue by fergyfresh** [rumpelsepp/pynote#35]
Currently the way the man page reads you have to attempt to create a new note and then, one-by-one, fix all the errors it spits back to you. 

Wouldn't it be more beneficial to have it create these things on a new note.

So it would be more like this:
    create new note
    created .notes dir
    created .notes/.trash dir

and then if there were errors doing this,
    create new note
    couldn't create .notes dir for random reason
    couldn't create .notes/.trash dir

Just a thought...

**Comment by rumpelsepp** [comment]
It is cool that there are some folks out there who actually seem to use `pynote`. That's nice!
I'll think about this, thx. :)

**Comment by arabar** [comment]
Sounds reasonable, +1.

**Comment by arabar** [comment]
I did commit some fix to #35 :)

**Comment by rumpelsepp** [comment]
I close this on favor of #36 which will get merged tomorrow or so.
